export * from './ciudades.repository';
export * from './cliente.repository';
export * from './contacto.repository';
export * from './empleados.repository';
export * from './inmuebles.repository';
export * from './registro.repository';
export * from './rol.repository';
export * from './tipo-inmueble.repository';
export * from './tipo-solicitud.repository';
