export * from './rol.model';
export * from './empleados.model';
export * from './registro.model';
export * from './cliente.model';
export * from './inmuebles.model';
export * from './tipo-solicitud.model';
export * from './tipo-inmueble.model';
export * from './ciudades.model';
export * from './contacto.model';
